# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dev_docs',
                'doc_host': 'https://sharflow.github.io',
                'git_url': 'https://github.com/sharflow/dev_docs',
                'lib_path': 'dev_docs'},
  'syms': {'dev_docs.core': {'dev_docs.core.foo': ('core.html#foo', 'dev_docs/core.py')}}}